language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository

env:
- TERM=dumb

before_script:
- 'echo $JAVA_OPTS'
- 'export JAVA_OPTS="-XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:+HeapDumpOnOutOfMemoryError -Xmx1024m"'

before_install:
  - git clone https://github.com/tilal6991/relay-jvm.git
  - git clone https://github.com/tilal6991/MemorizingTrustManager.git
